<a href="https://colab.research.google.com/github/DaminikaDz/Data_Ranking_Training_Dynamics/blob/main/src/colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
!wget https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz
!tar -xzf imagenette2-160.tgz

--2026-04-24 21:56:38--  https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.29.78, 52.216.38.40, 54.231.195.112, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.29.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99003388 (94M) [application/x-tar]
Saving to: ‘imagenette2-160.tgz’

imagenette2-160.tgz 100%[===================>]  94.42M  45.7MB/s    in 2.1s

2026-04-24 21:56:40 (45.7 MB/s) - ‘imagenette2-160.tgz’ saved [99003388/99003388]

In [5]:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch.nn.functional as F

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [14]:
!pip install torch torchvision tqdm scikit-learn pandas pillow -q

In [8]:
model = torch.hub.load("facebookresearch/dinov2", "dinov2_vitl14")
model = model.to(device)
model.eval()

Downloading: "https://github.com/facebookresearch/dinov2/zipball/main" to /root/.cache/torch/hub/main.zip

/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")

Downloading: "https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_pretrain.pth" to /root/.cache/torch/hub/checkpoints/dinov2_vitl14_pretrain.pth

100%|██████████| 1.13G/1.13G [00:10<00:00, 116MB/s]

DinoVisionTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14))
    (norm): Identity()
  )
  (blocks): ModuleList(
    (0-23): 24 x NestedTensorBlock(
      (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
      (attn): MemEffAttention(
        (qkv): Linear(in_features=1024, out_features=3072, bias=True)
        (proj): Linear(in_features=1024, out_features=1024, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (ls1): LayerScale()
      (drop_path1): Identity()
      (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=1024, out_features=4096, bias=True)
        (act): GELU(approximate='none')
        (fc2): Linear(in_features=4096, out_features=1024, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
      (ls2): LayerScale()
      (drop_path2): Identity()
    )
  )
  (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
  (head): Identity()
)

In [9]:
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [45]:
train_ds = datasets.ImageFolder("imagenette2-160/train", transform=transform)
val_ds = datasets.ImageFolder("imagenette2-160/val", transform=transform)

print(len(train_ds), len(val_ds))

9469 3925

In [13]:
train_loader = DataLoader(
    train_ds,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=64,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

In [14]:
def extract_embeddings(loader, model, device):
    all_embeddings = []
    all_labels = []
    all_paths = []

    with torch.inference_mode():
        for images, labels in tqdm(loader):
            images = images.to(device, non_blocking=True)

            emb = model(images)
            emb = F.normalize(emb, dim=1)

            all_embeddings.append(emb.cpu().numpy())
            all_labels.extend(labels.numpy())

    embeddings = np.vstack(all_embeddings)
    labels = np.array(all_labels)

    return embeddings, labels

In [15]:
train_embeddings, train_labels = extract_embeddings(train_loader, model, device)
val_embeddings, val_labels = extract_embeddings(val_loader, model, device)

print(train_embeddings.shape)
print(val_embeddings.shape)

100%|██████████| 148/148 [07:37<00:00,  3.09s/it]
100%|██████████| 62/62 [03:12<00:00,  3.10s/it]

(9469, 1024)
(3925, 1024)

In [17]:
!git clone https://github.com/facebookresearch/ssl-data-curation.git
%cd ssl-data-curation

Cloning into 'ssl-data-curation'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 35 (delta 3), reused 0 (delta 0), pack-reused 20 (from 1)
Receiving objects: 100% (35/35), 1.97 MiB | 5.96 MiB/s, done.
Resolving deltas: 100% (5/5), done.
/content/ssl-data-curation

In [22]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.2 (from -r requirements.txt (line 2))
  Downloading https://download-r2.pytorch.org/whl/cu118/torch-2.2.0%2Bcu118-cp312-cp312-linux_x86_64.whl (811.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 811.6/811.6 MB 2.0 MB/s eta 0:00:00
Collecting matplotlib==3.8.2 (from -r requirements.txt (line 3))
  Downloading matplotlib-3.8.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting scipy==1.11.4 (from -r requirements.txt (line 4))
  Downloading scipy-1.11.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 3.6 MB/s eta 0:00:00
Collecting numpy==1.24.4 (from -r requirements.txt (line 5))
  Downloading numpy-1.24.4.tar.gz (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 96.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [18]:
from src.clusters import HierarchicalCluster
from src import (
    hierarchical_kmeans_gpu as hkmg,
    hierarchical_sampling as hs
)

In [19]:
data=torch.tensor(train_embeddings, device="cuda", dtype=torch.float32)

In [23]:
np.Inf = np.inf

In [33]:
clusters = hkmg.hierarchical_kmeans_with_resampling(
  data=torch.tensor(data, device="cuda", dtype=torch.float32),
  n_clusters=[1000, 300, 100],
  n_levels=3,
  sample_sizes=[5, 3, 2],
  verbose=True,
)

cl = HierarchicalCluster.from_dict(clusters)
sampled_indices = hs.hierarchical_sampling(cl, target_size=2000)

/tmp/ipykernel_10298/434840230.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data=torch.tensor(data, device="cuda", dtype=torch.float32),

Kmeans++ initialization: 100%|██████████| 999/999 [00:00<00:00, 1459.20it/s]
Hierarchical k-means resampling steps: 100%|██████████| 10/10 [00:58<00:00,  5.84s/it]
Kmeans++ initialization: 100%|██████████| 299/299 [00:00<00:00, 1289.21it/s]
Hierarchical k-means resampling steps: 100%|██████████| 10/10 [00:17<00:00,  1.74s/it]
Kmeans++ initialization: 100%|██████████| 99/99 [00:00<00:00, 1932.12it/s]
Hierarchical k-means resampling steps: 100%|██████████| 10/10 [00:06<00:00,  1.58it/s]
Hierarchical sampling from clusters: 100%|██████████| 100/100 [00:00<00:00, 2074.20it/s]

In [34]:
subset_labels = train_labels[sampled_indices]

pd.Series(subset_labels).value_counts().sort_index()

0    192
1    177
2    199
3    199
4    333
5    188
6    176
7    173
8    175
9    188
Name: count, dtype: int64

In [36]:
from torch.utils.data import Subset
import torch.nn as nn
from torchvision.models import resnet50, ResNet50_Weights

In [46]:
hkm_subset_ds = Subset(train_ds, sampled_indices)

In [38]:
batch_size = 64

full_train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
hkm_train_loader = DataLoader(hkm_subset_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)

val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
num_classes = len(train_ds.classes)

def create_resnet50(frozen=True):
    weights = ResNet50_Weights.IMAGENET1K_V2
    model = resnet50(weights=weights)

    if frozen:
        for p in model.parameters():
            p.requires_grad = False

    model.fc = nn.Linear(model.fc.in_features, num_classes)

    return model.to(device)

In [40]:
def train_one_epoch(model, loader, optimizer, criterion):
    model.train()
    total_loss, correct, total = 0, 0, 0

    for images, labels in tqdm(loader):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item() * images.size(0)
        correct += (outputs.argmax(1) == labels).sum().item()
        total += labels.size(0)

    return total_loss / total, correct / total


def evaluate(model, loader, criterion):
    model.eval()
    total_loss, correct, total = 0, 0, 0

    with torch.inference_mode():
        for images, labels in loader:
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            outputs = model(images)
            loss = criterion(outputs, labels)

            total_loss += loss.item() * images.size(0)
            correct += (outputs.argmax(1) == labels).sum().item()
            total += labels.size(0)

    return total_loss / total, correct / total

In [41]:
def run_experiment(name, train_loader, frozen=True, epochs=5):
    model = create_resnet50(frozen=frozen)
    criterion = nn.CrossEntropyLoss()

    if frozen:
        optimizer = torch.optim.AdamW(model.fc.parameters(), lr=1e-3)
    else:
        optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)

    history = []

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion)
        val_loss, val_acc = evaluate(model, val_loader, criterion)

        print(
            f"{name} | epoch {epoch+1}/{epochs} | "
            f"train_acc={train_acc:.4f} | val_acc={val_acc:.4f}"
        )

        history.append({
            "experiment": name,
            "epoch": epoch + 1,
            "frozen": frozen,
            "train_loss": train_loss,
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc
        })

    return pd.DataFrame(history)

In [47]:
results = []

results.append(run_experiment("full_frozen", full_train_loader, frozen=True, epochs=5))
results.append(run_experiment("hkm2000_frozen", hkm_train_loader, frozen=True, epochs=5))

results.append(run_experiment("full_unfrozen", full_train_loader, frozen=False, epochs=5))
results.append(run_experiment("hkm2000_unfrozen", hkm_train_loader, frozen=False, epochs=5))

results_df = pd.concat(results, ignore_index=True)

results_df

100%|██████████| 148/148 [00:36<00:00,  4.06it/s]

full_frozen | epoch 1/5 | train_acc=0.9333 | val_acc=0.9755

100%|██████████| 148/148 [00:33<00:00,  4.39it/s]

full_frozen | epoch 2/5 | train_acc=0.9799 | val_acc=0.9819

100%|██████████| 148/148 [00:34<00:00,  4.34it/s]

full_frozen | epoch 3/5 | train_acc=0.9874 | val_acc=0.9839

100%|██████████| 148/148 [00:34<00:00,  4.29it/s]

full_frozen | epoch 4/5 | train_acc=0.9922 | val_acc=0.9829

100%|██████████| 148/148 [00:34<00:00,  4.26it/s]

full_frozen | epoch 5/5 | train_acc=0.9930 | val_acc=0.9857

100%|██████████| 32/32 [00:07<00:00,  4.43it/s]

hkm2000_frozen | epoch 1/5 | train_acc=0.7255 | val_acc=0.9233

100%|██████████| 32/32 [00:08<00:00,  3.91it/s]

hkm2000_frozen | epoch 2/5 | train_acc=0.9280 | val_acc=0.9603

100%|██████████| 32/32 [00:07<00:00,  4.02it/s]

hkm2000_frozen | epoch 3/5 | train_acc=0.9485 | val_acc=0.9664

100%|██████████| 32/32 [00:07<00:00,  4.42it/s]

hkm2000_frozen | epoch 4/5 | train_acc=0.9675 | val_acc=0.9707

100%|██████████| 32/32 [00:08<00:00,  3.99it/s]

hkm2000_frozen | epoch 5/5 | train_acc=0.9735 | val_acc=0.9740

100%|██████████| 148/148 [01:38<00:00,  1.50it/s]

full_unfrozen | epoch 1/5 | train_acc=0.5828 | val_acc=0.9271

100%|██████████| 148/148 [01:38<00:00,  1.50it/s]

full_unfrozen | epoch 2/5 | train_acc=0.9510 | val_acc=0.9641

100%|██████████| 148/148 [01:38<00:00,  1.50it/s]

full_unfrozen | epoch 3/5 | train_acc=0.9688 | val_acc=0.9732

100%|██████████| 148/148 [01:39<00:00,  1.49it/s]

full_unfrozen | epoch 4/5 | train_acc=0.9808 | val_acc=0.9806

100%|██████████| 148/148 [01:38<00:00,  1.50it/s]

full_unfrozen | epoch 5/5 | train_acc=0.9883 | val_acc=0.9819

100%|██████████| 32/32 [00:21<00:00,  1.50it/s]

hkm2000_unfrozen | epoch 1/5 | train_acc=0.1550 | val_acc=0.2031

100%|██████████| 32/32 [00:21<00:00,  1.50it/s]

hkm2000_unfrozen | epoch 2/5 | train_acc=0.4060 | val_acc=0.4459

100%|██████████| 32/32 [00:21<00:00,  1.48it/s]

hkm2000_unfrozen | epoch 3/5 | train_acc=0.6000 | val_acc=0.6247

100%|██████████| 32/32 [00:21<00:00,  1.51it/s]

hkm2000_unfrozen | epoch 4/5 | train_acc=0.7340 | val_acc=0.7613

100%|██████████| 32/32 [00:21<00:00,  1.51it/s]

hkm2000_unfrozen | epoch 5/5 | train_acc=0.8330 | val_acc=0.8540

          experiment  epoch  frozen  train_loss  train_acc  val_loss   val_acc
0        full_frozen      1    True    0.511703   0.933256  0.157267  0.975541
1        full_frozen      2    True    0.110576   0.979935  0.091505  0.981911
2        full_frozen      3    True    0.067298   0.987433  0.071351  0.983949
3        full_frozen      4    True    0.048179   0.992185  0.065208  0.982930
4        full_frozen      5    True    0.036549   0.993030  0.056240  0.985732
5     hkm2000_frozen      1    True    1.409272   0.725500  0.914328  0.923312
6     hkm2000_frozen      2    True    0.560276   0.928000  0.484759  0.960255
7     hkm2000_frozen      3    True    0.343913   0.948500  0.342188  0.966369
8     hkm2000_frozen      4    True    0.249981   0.967500  0.266004  0.970701
9     hkm2000_frozen      5    True    0.196507   0.973500  0.218791  0.974013
10     full_unfrozen      1   False    1.916368   0.582849  1.311950  0.927134
11     full_unfrozen      2   False    0.711916   0.950998  0.306148  0.964076
12     full_unfrozen      3   False    0.224217   0.968846  0.155227  0.973248
13     full_unfrozen      4   False    0.124662   0.980779  0.107647  0.980637
14     full_unfrozen      5   False    0.075838   0.988278  0.082735  0.981911
15  hkm2000_unfrozen      1   False    2.279335   0.155000  2.242431  0.203057
16  hkm2000_unfrozen      2   False    2.128144   0.406000  2.117787  0.445860
17  hkm2000_unfrozen      3   False    1.956182   0.600000  1.962602  0.624713
18  hkm2000_unfrozen      4   False    1.734754   0.734000  1.753124  0.761274
19  hkm2000_unfrozen      5   False    1.480824   0.833000  1.510007  0.854013

In [48]:
new_result = run_experiment("hkm2000_unfrozen", hkm_train_loader, frozen=False, epochs=10)

100%|██████████| 32/32 [00:22<00:00,  1.39it/s]

hkm2000_unfrozen | epoch 1/10 | train_acc=0.1130 | val_acc=0.1890

100%|██████████| 32/32 [00:20<00:00,  1.55it/s]

hkm2000_unfrozen | epoch 2/10 | train_acc=0.3635 | val_acc=0.3896

100%|██████████| 32/32 [00:21<00:00,  1.52it/s]

hkm2000_unfrozen | epoch 3/10 | train_acc=0.5915 | val_acc=0.5710

100%|██████████| 32/32 [00:21<00:00,  1.49it/s]

hkm2000_unfrozen | epoch 4/10 | train_acc=0.7630 | val_acc=0.7442

100%|██████████| 32/32 [00:21<00:00,  1.52it/s]

hkm2000_unfrozen | epoch 5/10 | train_acc=0.8535 | val_acc=0.8573

100%|██████████| 32/32 [00:21<00:00,  1.50it/s]

hkm2000_unfrozen | epoch 6/10 | train_acc=0.9050 | val_acc=0.9113

100%|██████████| 32/32 [00:21<00:00,  1.51it/s]

hkm2000_unfrozen | epoch 7/10 | train_acc=0.9330 | val_acc=0.9320

100%|██████████| 32/32 [00:21<00:00,  1.51it/s]

hkm2000_unfrozen | epoch 8/10 | train_acc=0.9455 | val_acc=0.9429

100%|██████████| 32/32 [00:21<00:00,  1.50it/s]

hkm2000_unfrozen | epoch 9/10 | train_acc=0.9570 | val_acc=0.9503

100%|██████████| 32/32 [00:21<00:00,  1.51it/s]

hkm2000_unfrozen | epoch 10/10 | train_acc=0.9630 | val_acc=0.9513

In [51]:
new_result

         experiment  epoch  frozen  train_loss  train_acc  val_loss   val_acc
0  hkm2000_unfrozen      1   False    2.290371     0.1130  2.246793  0.189045
1  hkm2000_unfrozen      2   False    2.143022     0.3635  2.126994  0.389554
2  hkm2000_unfrozen      3   False    1.971374     0.5915  1.980823  0.570955
3  hkm2000_unfrozen      4   False    1.760891     0.7630  1.793502  0.744204
4  hkm2000_unfrozen      5   False    1.532789     0.8535  1.614839  0.857325
5  hkm2000_unfrozen      6   False    1.309027     0.9050  1.367134  0.911338
6  hkm2000_unfrozen      7   False    1.053981     0.9330  1.059143  0.931975
7  hkm2000_unfrozen      8   False    0.807287     0.9455  0.784008  0.942930
8  hkm2000_unfrozen      9   False    0.605654     0.9570  0.572767  0.950318
9  hkm2000_unfrozen     10   False    0.460984     0.9630  0.443734  0.951338